version: '3.1'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: koa_blog
    container_name: mydb

  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  app:
    build: .
    depends_on:
      - db
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DB_HOST: mydb
      DB_USER: root
      DB_PASSWORD: 12345678
      DB_NAME: koa_blog
networks:
  default:
    driver: bridge
